### PR TITLE
Fixed RegEx to match newline

### PR DESCRIPTION
**Pull request by BrutalBirdie**
Updated the RegEx to match newlines.
Also added a new match so the last matched group will be used.
See Issue #5 for more information.

### CODE REVIEW

**Comment by indilo53** [comment]
Seems good I don't tested it but will check later if there is problems, thanks for contribution !

**Comment by BrutalBirdie** [comment]
@indilo53 Could you just build it? (the .exe) I would gladly test it and report back :)

**Comment by BrutalBirdie** [comment]
Okay I am **F***** done. I tried now for 2 more hours to build this.
It fails all the time when trying to install node-lua from node-gyp.
I tried 20 suggested fixes for this issue.
I used the official node-lua repo instead of yours.
I just wanted to debug this, I am done. Hope to hear from you again
@indilo53 


Here you have the stupid error dump. I give up. Your turn.
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" wurde mit dem Code 1 beendet. [C:\Users\eha-t
ower\Develop\fxserver-resource-scrambler\node_modules\node-lua\build\nodelua.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\eha-tower\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\eha-tower\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\eha-tower\Develop\fxserver-resource-scrambler\node_modules\node-lua
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN resource-scrambler@0.2.6 No repository field.
npm WARN resource-scrambler@0.2.6 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-lua@git+https://github.com/medaeus245/node-lua#13b1b830210256fc6bd24502ec23e5b63b07afd6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-lua@git+https://github.com/medaeus245/node-lua#13b1b830210256fc6bd24502ec23e5b63b07afd6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\eha-tower\AppData\Roaming\npm-cache\_logs\2019-06-20T01_02_31_972Z-debug.log
```

**Comment by indilo53** [comment]
Yeah I saw there is some v8-related things who don't followed node-gyp environnment updates in the repo. At least, with nodejs 12 and the provided node-gyp I can't compile.

Can be others things too but I spotted this one.

I will check it later in the week.

**Comment by BrutalBirdie** [comment]
> 
> 
> Yeah I saw there is some v8-related things who don't followed node-gyp environnment updates in the repo. At least, with nodejs 12 and the provided node-gyp I can't compile.
> 
> Can be others things too but I spotted this one.
> 
> I will check it later in the week.

I used nvm to install nodejs version 10.0.0
Did this npm install -g windows-build-tools
npm install -g node-lua

This worked (finally)

Went into the repo and did npm install which also worked.
but when I try to run node 
```
node index.js
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module './build/Debug/nodelua'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\eha-tower\Develop\fxserver-resource-scramble
r\node_modules\node-lua\index.js:6:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```
this happens.
node-gyp rebuild will result in
```
gyp: binding.gyp not found (cwd: C:\Users\eha-tower\Develop\fxserver-resource-scrambler) while trying to load binding.gyp
```
Your turn @indilo53  ;)

**Comment by RikoDEV** [comment]
^^ Any idea how to fix this?

**Pull request merged**
